<?php
// pattern (regex, no delimiters) => page file under /pages  |  [page file, param names...]
return [
    // public
    ''              => 'public/home',
    'services'      => 'public/services',
    'how-it-works'  => 'public/how_it_works',
    'about'         => 'public/about',
    'privacy'       => 'public/privacy',
    'terms'         => 'public/terms',
    'disclaimer'    => 'public/disclaimer',
    'guides'        => 'public/guides',
    'guides/([a-z0-9-]+)' => ['public/guide', 'slug'],
    'providers/(\d+)'     => ['public/provider', 'id'],
    'api/providers' => 'api/providers',
    // auth
    'login'    => 'auth/login',
    'register' => 'auth/register',
    'logout'   => 'auth/logout',
    // user
    'user'                   => 'user/home',
    'user/providers'         => 'user/providers',
    'user/providers/(\d+)'   => ['user/provider', 'id'],
    'user/book/(\d+)'        => ['user/book', 'id'],
    'user/bookings'          => 'user/bookings',
    'user/favorites'         => 'user/favorites',
    'user/profile'           => 'user/profile',
    'user/rating'            => 'user/rating',
    'user/complaints'        => 'user/complaints',
    'user/notifications'     => 'user/notifications',
    'user/payments'          => 'user/payments',
    'user/api'               => 'user/api',
    // provider
    'provider'               => 'provider/dashboard',
    'provider/profile'       => 'provider/profile',
    'provider/settings'      => 'provider/settings',
    'provider/services'      => 'provider/services',
    'provider/availability'  => 'provider/availability',
    'provider/requests'      => 'provider/requests',
    'provider/bookings'      => 'provider/bookings',
    'provider/reviews'       => 'provider/reviews',
    'provider/verification'  => 'provider/verification',
    'provider/payments'      => 'provider/payments',
    'provider/notifications' => 'provider/notifications',
    'provider/documents/(\d+)' => ['provider/document', 'id'],
    // admin
    'admin'                       => 'admin/dashboard',
    'admin/users'                 => 'admin/users',
    'admin/users/(\d+)'           => ['admin/user_view', 'id'],
    'admin/users/(\d+)/edit'      => ['admin/user_edit', 'id'],
    'admin/providers'             => 'admin/providers',
    'admin/providers/(\d+)'       => ['admin/provider_view', 'id'],
    'admin/providers/(\d+)/edit'  => ['admin/provider_edit', 'id'],
    'admin/verification'          => 'admin/verification',
    'admin/verification/(\d+)'    => ['admin/verification_review', 'id'],
    'admin/documents/(\d+)'       => ['admin/document', 'id'],
    'admin/services'              => 'admin/services',
    'admin/services/new'          => 'admin/service_edit',
    'admin/services/(\d+)/edit'   => ['admin/service_edit', 'id'],
    'admin/bookings'              => 'admin/bookings',
    'admin/payments'              => 'admin/payments',
    'admin/complaints'            => 'admin/complaints',
    'admin/complaints/(\d+)'      => ['admin/complaint_view', 'id'],
    'admin/api'                   => 'admin/api',
];
